org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true
kotlin.code.style=official

mc_version=1.21.1
neoforge_version=21.1.219
parchment_mappings_version=2024.11.17

mod_id=atmosphere
mod_version=1.0.<patch>
release_type=release
mod_name=Atmosphere
mod_author=possible_triangle
mod_description=library for localized weather systems
maven_group=com.possible-triangle
version_strategy=suffix_minecraft_version

repository=pssbletrngle/atmosphere
