[versions]
create-simulated = "1.2.1"

[libraries]
ponder = { group = "net.createmod.ponder", name = "ponder-neoforge", version = "1.0.82+mc1.21.1" }
registrate = { group = "com.tterrag.registrate", name = "Registrate", version = "MC1.21-1.3.0+67" }

sable = { group = "dev.ryanhcode.sable", name = "sable-neoforge-1.21.1", version = "1.2.2" }
create-simulated = { group = "dev.simulated_team.simulated", name = "simulated-neoforge-1.21.1", version.ref = "create-simulated" }
create-aeronautics = { group = "dev.eriksonn.aeronautics", name = "aeronautics-neoforge-1.21.1", version.ref = "create-simulated" }
