# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.82</version>
#    <timestamp>2026-05-31T12:04:08.400Z</timestamp>
#    <hash>9d521ee415ea61ee</hash>
# </meta>

blank_issues_enabled: false
